.Dd $Mdocdate$
.Dt qsh(1)
.Os
.Sh qsh
.Nm Qshell
.Nd A syntaxically strict shell language.
.\" .Sh LIBRARY
.\" For sections 2, 3, and 9 only.
.\" Not used in OpenBSD.
.Sh SYNOPSIS
.Nm qsh
.Op Ar
.Op Fl c Ar code
.Sh INTRODUCTION
An introduction to Qshell may be found at qsh-intro(1)
.Sh DESCRIPTION
.Nm
is a syntaxically strict shell language that isn't *necessarily* POSIX compliant.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh IMPLEMENTATION NOTES
.\" Not used in OpenBSD.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
An exit code of 4 means that you have a syntax error. Don't fret, though, as the error will probably provide a hint of how to resolve it.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.\" .Sh SEE ALSO
.\" .Xr foobar 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
