name: Build code
on:
  push:
    branches: ['trunk']
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          run_install: true
          version: '6.10.3'

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Build source and commit
        run: bash scripts/build.sh
