name: Build code
on: 
  push:
    branches: ['trunk']
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
    
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          run_install: true
          version: '6.10.3'
          
      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
          
      - name: Build source and commit
        run: |
          set -x
          git pull
          git reset --hard origin/trunk
          git log -n 10 --format="%h %s"
          tsc -p tsconfig.json
          mkdir tmp
          bash scripts/changelog.sh > CHANGELOG.md.new
          mv docs tmp
          git checkout build
          echo "New changelog:" | cat - CHANGELOG.md.new
          mv CHANGELOG.md.new CHANGELOG.md
          mv tmp/docs .
          rm -rf tmp
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git commit -m "build ${GITHUB_SHA}" --author "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          git push origin build
